################################################################################
# Sensors
# https://home-assistant.io/components/sensor/
################################################################################

## Weather prediction
## https://www.home-assistant.io/components/sensor.yr/
#  - platform: yr
#    name: Weather
#    monitored_conditions:
#      - temperature
#      - symbol
#      # - precipitation
#      # - windSpeed
#      - pressure
#      # - windDirection
#      # - humidity
#      # - fog
#      # - cloudiness
#      # - lowClouds
#      # - mediumClouds
#      # - highClouds
#      # - dewpointTemperature


  - platform: time_date
    display_options:
    - 'time'
    - 'date'
    - 'date_time'
#    - 'time_date'
#    - 'time_utc'
#    - 'beat'
