################################################################################
# Shell commands
# https://www.home-assistant.io/components/shell_command/
################################################################################
